### ISSUE TITLE
Name of raft mascot, Wikipedia additions

### ISSUE THREAD

**Issue by catleeball** [raft/logo#5]
Hi everyone,

Does the Raft logo/mascot have a name?

Also, just small FYI: I uploaded the raft to Wikimedia and updated a couple wiki pages to include it. Please feel free to edit, add, or remove things if you'd like.

- https://commons.wikimedia.org/wiki/File:Raft_Consensus_Algorithm_Mascot_on_transparent_background.svg
- https://commons.wikimedia.org/wiki/File:Raft_Consensus_Algorithm_Mascot_with_Background.svg
- https://en.wikipedia.org/wiki/Raft_(algorithm)
- https://en.wikipedia.org/wiki/List_of_computing_mascots#R

Thanks!

**Comment by ongardie** [comment]
Hi @catleeball, thanks for the updates. I don't think we ever named the logo. Annie Ruygt called the original file `raft-cutie.png`, but I don't think of that as its name.

**Comment by catleeball** [comment]
Got it, no worries if it doesn't have a name! Just thought I'd ask to check. :) Thanks!
